apiVersion: v1
kind: Secret
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:5cmR9mYcS3rNRskfEfxxB3K9RgOC/b9uFerjfwnkkuINld5A7kggAhe0DNSt4/iPJe6TMImGjYrwsEyZ7DwzXlVMxT0qjDy0J2xE+glZtm37zNiKBD69zDjru3/G84DqrbUgbfbG02O+5l68EXJ+I8mxWCc8WdSd61a4wQ==,iv:ingx06kXI2NLYY4HgbTaQeWTYmkx7zauy7ZhEJjGfQc=,tag:64TRGJViPl8lOTFJZgZfgQ==,type:str]
metadata:
    name: regcred
    namespace: oneball
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16rspnzt6j2qxa2587t6umh9qykrqu2amrr0hx9xt2z7elyky3a3q4p5s7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UXFhQ05zSHp3VW5TaE5a
            a0ZOSXpvQVZEQnpNejQxTFpXaC9EL0ViZVI4CjVFWXJEdWhGK0JSZmZOaURoUFdI
            NTJldy9NV2RKMnVtUDlOQzJqZ09oMEEKLS0tIGFScktLOVFTZHJNWmRabnRYYitz
            V0FLMWlUNkV1NnQrQ3NQQmdaTUcwTDgK7GeLf3eNnTQ9Nzj5wdR7YS3Uo7/T1yjT
            o1Z3FzhXXu2uNc0b7+x7mCW0s/+IfLmXrgZXnrYxmqqeO1zdnpQc4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17gp6lqd6u457fjmqptyetnnhy8tx93hqt2juejlvrmujc54acces06dk4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdHlmbVlvR05UYkVZamVG
            Q0NvZVRCVWpHdnVIalBYY1NpRHYxOEtTNmdvCjRrRzljR2kyZEVKNjFYVlNaSXVF
            VW9PQTV2UnhCZ3hhNFJaZEw5VjdrRDgKLS0tIDdmbDJaUFVvNDdZR3RldVphK044
            Z01SOFBPOXNON1Zyb0NnWllHeHpGWUUK3P9I2c8copsiANzHZ9/6O9XLRlU8Lvth
            yFjEr94iJbW7pfiBqhpkJ+UxsDok05chTnKarNi4G3OkF/YvBQVPwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ssqw7t6pnmlpsrx4tkpucqtzj5vzksmtcwkgp3prp5rspyvyk5tq0u32cs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWtmTFpDNVJPOGRtOUJB
            T0V4UlUvY1N4NzhHbmFNdHdLODlWbVpnQWwwCnF6ekNDWTFDR3Z1N1JuSW1BVnZ5
            RlM5cFhZN3BGZXl2VWJDNUVkVTRjRk0KLS0tIEVqWGRFMEpKVmVURlNPWGYwSkUw
            QmszWDRVNVZubDhYWjNZSTNHNU9Uc0EKAiBAyptx8L4ExRyHlRwNDEWP/wMY6ts7
            LtLuoIXPs975aeioBlw0oX8xGgnWygx9e1UsnJ4ms5uVdE3h7dN83A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age194m4ryt3tda6vmk7czxm362rumy9y9ngq5lsx50pdjzmfd0flg7q6ngszm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdHd2KzQ0Y0hRQlJQOVl6
            MlB5K3NsdjFwVzNJeXBnME4vY3NubEFIRlRBClhNUlZQRStrRzhVYkljTlpMZElp
            T0EzbTRheHNYcWlveEljdFJlVzFQQm8KLS0tIDMwT21VMlBHWkE2aWxUMDFISGJn
            VEp3SGhYUFFmWjJ3cGNNTlJVT3hjN3cKlQOV3lxD80IqGslpikCRiPOUxRSkKTcr
            WhsyChwGzYIa0VSLsG+uWQM8iZNRydNRTPrI2gFqV46nOLYXH0YJbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T09:43:39Z"
    mac: ENC[AES256_GCM,data:TV8bs5C5+EU8mNwy1rIN5ark5xPxhJ4XBl/V/nIKT+m68TCNkUqYeipxM1zpazqszwmElXkNpHt2Yqz3kPVS29BjP1etmWkUsSTfIzu+R5vE8CfjANBYxSt5vSTD41+YF14PgSDJQ8l9J4mvN2xNOQPwItYrn5odtUlkI9RI3yA=,iv:llN3GaloImsqJhss88SWB2Zj9fc7IyAKA9MSNL3LXHg=,tag:nme/u+hv0JspQfvGAE2nCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
