apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/part-of: oneball
    app.kubernetes.io/name: app
  name: app
  namespace: oneball
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: oneball
      app.kubernetes.io/name: app
  serviceName: app
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: oneball
        app.kubernetes.io/name: app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: "dh2wltsh.gra7.container-registry.ovh.net/pole-edition/oneball:latest"
          volumeMounts:
            - name: data
              mountPath: /app/backup
            - name: config
              mountPath: /app/static/config.json
              subPath: config.json
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: wss
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          configMap:
            name: config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: oneball
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: csi-cinder-high-speed
